/*
 * This file is generated by jOOQ.
 */
package com.example.demoapp;


import com.example.demoapp.tables.Company;
import com.example.demoapp.tables.records.CompanyRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = Internal.createUniqueKey(Company.COMPANY, DSL.name("KEY_company_PRIMARY"), new TableField[] { Company.COMPANY.COMPANY_ID }, true);
    public static final UniqueKey<CompanyRecord> KEY_COMPANY_UK_I2JCJCEJGNWUAFXOFWMGOSD13 = Internal.createUniqueKey(Company.COMPANY, DSL.name("KEY_company_UK_i2jcjcejgnwuafxofwmgosd13"), new TableField[] { Company.COMPANY.COMPANY_CODE }, true);
}
