/*
 * This file is generated by jOOQ.
 */
package com.example.demoapp;


import com.example.demoapp.tables.Company;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;
}
