/*
 * This file is generated by jOOQ.
 */
package com.example.demoapp.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long companyId;
    private String companyCode;
    private String bizName;
    private String bizPlace;

    public CompanyEntity() {}

    public CompanyEntity(CompanyEntity value) {
        this.companyId = value.companyId;
        this.companyCode = value.companyCode;
        this.bizName = value.bizName;
        this.bizPlace = value.bizPlace;
    }

    public CompanyEntity(
        Long companyId,
        String companyCode,
        String bizName,
        String bizPlace
    ) {
        this.companyId = companyId;
        this.companyCode = companyCode;
        this.bizName = bizName;
        this.bizPlace = bizPlace;
    }

    /**
     * Getter for <code>company.company_id</code>.
     */
    public Long getCompanyId() {
        return this.companyId;
    }

    /**
     * Setter for <code>company.company_id</code>.
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * Getter for <code>company.company_code</code>.
     */
    public String getCompanyCode() {
        return this.companyCode;
    }

    /**
     * Setter for <code>company.company_code</code>.
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * Getter for <code>company.biz_name</code>.
     */
    public String getBizName() {
        return this.bizName;
    }

    /**
     * Setter for <code>company.biz_name</code>.
     */
    public void setBizName(String bizName) {
        this.bizName = bizName;
    }

    /**
     * Getter for <code>company.biz_place</code>.
     */
    public String getBizPlace() {
        return this.bizPlace;
    }

    /**
     * Setter for <code>company.biz_place</code>.
     */
    public void setBizPlace(String bizPlace) {
        this.bizPlace = bizPlace;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CompanyEntity other = (CompanyEntity) obj;
        if (this.companyId == null) {
            if (other.companyId != null)
                return false;
        }
        else if (!this.companyId.equals(other.companyId))
            return false;
        if (this.companyCode == null) {
            if (other.companyCode != null)
                return false;
        }
        else if (!this.companyCode.equals(other.companyCode))
            return false;
        if (this.bizName == null) {
            if (other.bizName != null)
                return false;
        }
        else if (!this.bizName.equals(other.bizName))
            return false;
        if (this.bizPlace == null) {
            if (other.bizPlace != null)
                return false;
        }
        else if (!this.bizPlace.equals(other.bizPlace))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.companyId == null) ? 0 : this.companyId.hashCode());
        result = prime * result + ((this.companyCode == null) ? 0 : this.companyCode.hashCode());
        result = prime * result + ((this.bizName == null) ? 0 : this.bizName.hashCode());
        result = prime * result + ((this.bizPlace == null) ? 0 : this.bizPlace.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CompanyEntity (");

        sb.append(companyId);
        sb.append(", ").append(companyCode);
        sb.append(", ").append(bizName);
        sb.append(", ").append(bizPlace);

        sb.append(")");
        return sb.toString();
    }
}
