spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demosys?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: demoadmin
    password: "#Bagabondo13"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    problemdetails:
      enabled: true
app:
  baseUrl: https://example.com